box = "ubuntu/xenial64"
Vagrant.configure("2") do |config|
  config.vm.box = box
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
    set -e
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get install -y --no-install-recommends ansible git

    rm -rf ansible-isucon
    git clone https://github.com/d9magai/ansible-isucon.git
    (
      cd ansible-isucon/isucon7-qualifier
      PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ansible-playbook -i local site.yml
    )
    rm -rf ansible-isucon
  SHELL
end
